version: '3.8'

services:
  db:
    image: postgres:15
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - paperless_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped

  paperless:
    image: paperlessngx/paperless-ngx:latest
    container_name: paperless
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - paperless_data:/usr/src/paperless/paperless-ngx/data
      - paperless_media:/usr/src/paperless/paperless-ngx/media
      - paperless_consume:/usr/src/paperless/paperless-ngx/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_TIME_ZONE: America/New_York
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
    restart: unless-stopped

volumes:
  paperless_db_data:
  paperless_data:
  paperless_media:
  paperless_consume:
