version: '3.8'

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - "8080:80"
    volumes:
      - ./conf.yml:/app/public/conf.yml
    restart: unless-stopped
