version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: 'a_secure_master_key'
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

volumes:
  meili_data:
