version: '3.1'

services:
  archivebox:
    image: archivebox/archivebox:latest
    command: server --quick-init 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    environment:
      - ALLOWED_HOSTS=*
      - SECRET_KEY=devsecret
      - DEBUG=true
