version: '3.3'

services:
  archivebox:
    image: archivebox/archivebox:latest
    container_name: archivebox
    ports:
      - "8000:8000"
    volumes:
      - archivebox-data:/data
    environment:
      - ALLOWED_HOSTS=*
      - SECRET_KEY=dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    restart: unless-stopped
    command: server --quick-init 0.0.0.0:8000

volumes:
  archivebox-data: