version: "3"

services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    command: "web"
    ports:
      - "3000:3000"
      - "7878:7878"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://bitmagnet:bitmagnet@postgres:5432/bitmagnet
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=info
    volumes:
      - ./data:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bitmagnet
      POSTGRES_PASSWORD: bitmagnet
      POSTGRES_DB: bitmagnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  pgdata:
