version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mayan-postgres
    environment:
      - POSTGRES_DB=mayan
      - POSTGRES_USER=mayan
      - POSTGRES_PASSWORD=mayanpass
    volumes:
      - mayan_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mayan:
    image: mayanedms/mayanedms:latest
    container_name: mayan-edms
    depends_on:
      - postgres
    environment:
      - MAYAN_DATABASE_ENGINE=django.db.backends.postgresql
      - MAYAN_DATABASE_NAME=mayan
      - MAYAN_DATABASE_USER=mayan
      - MAYAN_DATABASE_PASSWORD=mayanpass
      - MAYAN_DATABASE_HOST=postgres
    ports:
      - "8000:8000"
    volumes:
      - mayan_media:/var/lib/mayan
    restart: unless-stopped

volumes:
  mayan_postgres_data:
  mayan_media:
