version: '3.8'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    container_name: rocketchat
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - rocketchat_data:/app/uploads

  mongo:
    image: mongo:6.0
    container_name: rocketchat_mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"

  mongo-init-replica:
    image: mongo:6.0
    depends_on:
      - mongo
    entrypoint: >
      bash -c "for i in `seq 1 30`; do
        mongo mongo:27017 --eval 'rs.initiate()' && break || sleep 1;
      done"

volumes:
  rocketchat_data:
  mongodb_data: