version: '3.7'

services:
  baserow:
    image: baserow/baserow:1.34.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_data:/baserow/data
    environment:
      BASEROW_PUBLIC_URL: http://localhost
      DATABASE_USER: baserow
      DATABASE_PASSWORD: baserow
      DATABASE_NAME: baserow
      DATABASE_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: baserow
      POSTGRES_PASSWORD: baserow
      POSTGRES_DB: baserow
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  baserow_data:
  pgdata:
