version: '3.8'

services:
  redis:
    image: redis:7
    container_name: activepieces-redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: activepieces-postgres
    environment:
      POSTGRES_DB: activepieces
      POSTGRES_USER: activepieces
      POSTGRES_PASSWORD: activepieces
    volumes:
      - activepieces_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  activepieces:
    image: activepieces/activepieces:latest
    container_name: activepieces
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
    environment:
      DATABASE_URL: postgres://activepieces:activepieces@postgres:5432/activepieces
      REDIS_URL: redis://redis:6379
      AP_ENVIRONMENT: docker
    volumes:
      - activepieces_data:/root/.activepieces
    restart: unless-stopped

volumes:
  activepieces_db_data:
  activepieces_data:
