version: '3.7'

services:
  bytebase:
    image: bytebase/bytebase:3.7.1
    ports:
      - "8080:8080"
    volumes:
      - bytebase_data:/var/opt/bytebase
    environment:
      GOGC: "50"
      OPENSSL_CONF: /etc/ssl/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5m
      timeout: 60s

volumes:
  bytebase_data:
